-- Seed Data for System Goals and Badges
-- All 50 goals as specified, in exact order

-- Phase 1: The Quick-Start Sprint (Goals 1-5)
INSERT INTO system_goals (id, phase, title, description, completion_criteria, badge_name, difficulty_rank) VALUES
(1, 1, 'Welcome to Stashway', 'Log in and view your primary Overview dashboard for the first time.', '{"event_type": "overview_viewed", "threshold": 1, "time_window": null}'::jsonb, 'The Explorer', 1),
(2, 1, 'Foundation Layer', 'Add your first financial account or cash wallet (e.g., GBTI or a "Cash Wallet") to the Funds tab.', '{"event_type": "account_added", "threshold": 1, "time_window": null}'::jsonb, 'Anchor Point', 2),
(3, 1, 'Ready to Scan', 'Navigate to the "Upload" section and familiarise yourself with the receipt drag-and-drop area.', '{"event_type": "upload_viewed", "threshold": 1, "time_window": null}'::jsonb, 'Paperless Pioneer', 3),
(4, 1, 'First Contact', 'Ask the conversational AI a basic question, such as "What can you do?" or "Tell me about my spending".', '{"event_type": "ai_chat_used", "threshold": 1, "time_window": null}'::jsonb, 'Small Talker', 4),
(5, 1, 'Setting the Bar', 'Create your first custom spending limit or target amount in the Goals tab.', '{"event_type": "goal_created", "threshold": 1, "time_window": null}'::jsonb, 'Goal Setter', 5),

-- Phase 2: Basic Engagement (Goals 6-15)
(6, 2, 'Digital Snapshot', 'Use the AI scanner to upload and digitise your first physical receipt.', '{"event_type": "receipt_scanned", "threshold": 1, "time_window": null}'::jsonb, 'Scan Starter', 6),
(7, 2, 'Manual Entry', 'Manually add a transaction to the spending list for an item bought with cash.', '{"event_type": "transaction_added_manual", "threshold": 1, "time_window": null}'::jsonb, 'Hand-Crafted', 7),
(8, 2, 'Insight Seeker', 'View a "Spending Tip" notification on your dashboard regarding your recent habits.', '{"event_type": "tip_viewed", "threshold": 1, "time_window": null}'::jsonb, 'Advice Taker', 8),
(9, 2, 'The Archivist', 'Export your first PDF report of your spending history.', '{"event_type": "report_exported", "threshold": 1, "time_window": null, "format": "pdf"}'::jsonb, 'Record Keeper', 9),
(10, 2, 'The Organiser', 'Take an untracked "Receipts" transaction and assign it to a specific category like "Dining Out".', '{"event_type": "transaction_categorized", "threshold": 1, "time_window": null}'::jsonb, 'Clean Slate', 10),
(11, 2, 'Liquid Assets', 'Successfully add funds to a "Cash Wallet" to track your physical money.', '{"event_type": "cash_wallet_funds_added", "threshold": 1, "time_window": null}'::jsonb, 'Cash King', 11),
(12, 2, 'Weekly Watcher', 'Check your "Spent Last 7 Days" card on the Overview dashboard.', '{"event_type": "spending_viewed", "threshold": 1, "time_window": "7_days"}'::jsonb, 'Week One', 12),
(13, 2, 'Target Hit', 'Achieve your first "Average Daily" spend target for a single day.', '{"event_type": "daily_target_achieved", "threshold": 1, "time_window": "1_day"}'::jsonb, 'On the Mark', 13),
(14, 2, 'Detective', 'Use the search bar in the Spending tab to find a specific past purchase.', '{"event_type": "spending_searched", "threshold": 1, "time_window": null}'::jsonb, 'Item Finder', 14),
(15, 2, 'Concise Learner', 'Request a "short and concise version" of financial advice from the AI.', '{"event_type": "ai_chat_used", "threshold": 1, "time_window": null, "pattern": "short|concise"}'::jsonb, 'Point-to-Point', 15),

-- Phase 3: Intermediate Tracking (Goals 16-30)
(16, 3, 'Consistency Kickstart', 'Log at least one transaction every day for three consecutive days.', '{"event_type": "transaction_logged", "threshold": 3, "time_window": "3_days", "streak_type": "daily"}'::jsonb, 'Three-Day Streak', 16),
(17, 3, 'Scanner Pro', 'Successfully scan 5 receipts in a single week using the AI tool.', '{"event_type": "receipt_scanned", "threshold": 5, "time_window": "7_days"}'::jsonb, 'High Volume', 17),
(18, 3, 'Stash Starter', 'Maintain a total net worth above $50,000 GYD as tracked in the app for one week.', '{"event_type": "net_worth_threshold", "threshold": 50000, "time_window": "7_days", "comparison": "gte"}'::jsonb, 'Growing Stash', 18),
(19, 3, 'Smart Choice', 'Reduce your "Dining Out" category spending by 5% compared to your first week.', '{"event_type": "category_spending_reduced", "threshold": 5, "time_window": "7_days", "category": "Dining Out", "comparison": "percentage"}'::jsonb, 'Home Cook', 19),
(20, 3, 'Category Variety', 'Track spending across at least four different categories (e.g., Groceries, Health, Transport, Dining).', '{"event_type": "categories_used", "threshold": 4, "time_window": null}'::jsonb, 'Well-Rounded', 20),
(21, 3, 'Halfway Hero', 'Keep your "Spent Last 30 Days" goal in the green (under limit) for 15 days.', '{"event_type": "monthly_limit_maintained", "threshold": 15, "time_window": "30_days", "comparison": "under"}'::jsonb, 'Steady Hand', 21),
(22, 3, 'Multi-Tasker', 'Manage and update balances for at least three different wallets or accounts.', '{"event_type": "accounts_managed", "threshold": 3, "time_window": null}'::jsonb, 'Asset Manager', 22),
(23, 3, 'Month in Review', 'View a full month of spending data in the Spending tab.', '{"event_type": "spending_viewed", "threshold": 1, "time_window": "30_days"}'::jsonb, 'Calendar Master', 23),
(24, 3, 'Opportunity Knocker', 'Use the AI to identify your "biggest opportunity" for saving.', '{"event_type": "ai_chat_used", "threshold": 1, "time_window": null, "pattern": "opportunity|saving|save money"}'::jsonb, 'Opportunity Seeker', 24),
(25, 3, 'Week Warrior', 'Log spending for seven consecutive days without a break.', '{"event_type": "transaction_logged", "threshold": 7, "time_window": "7_days", "streak_type": "daily"}'::jsonb, 'Seven-Day Streak', 25),
(26, 3, 'Local Legend', 'Scan a receipt from a major local retailer like Massy Stores.', '{"event_type": "receipt_scanned", "threshold": 1, "time_window": null, "merchant_pattern": "massy|grocery|retail"}'::jsonb, 'Local Shopper', 26),
(27, 3, 'Data Analyst', 'Export a monthly spending report in a different format (e.g., CSV or PDF).', '{"event_type": "report_exported", "threshold": 1, "time_window": "30_days", "format": "csv"}'::jsonb, 'Report Master', 27),
(28, 3, 'Budget Architect', 'Set three different spending limits for three different categories simultaneously.', '{"event_type": "category_limits_set", "threshold": 3, "time_window": null}'::jsonb, 'Master Planner', 28),
(29, 3, 'Curious Mind', 'Ask the conversational AI about your spending in a specific category for the month.', '{"event_type": "ai_chat_used", "threshold": 1, "time_window": "30_days", "pattern": "category|spending|month"}'::jsonb, 'Inquiry Expert', 29),
(30, 3, 'Categorisation King', 'Ensure you have zero "Uncategorised" items at the end of a week.', '{"event_type": "uncategorized_zero", "threshold": 0, "time_window": "7_days"}'::jsonb, 'Sorting Specialist', 30),

-- Phase 4: Advanced Budgeting (Goals 31-45)
(31, 4, 'Fortnight Finisher', 'Maintain a 14-day logging streak.', '{"event_type": "transaction_logged", "threshold": 14, "time_window": "14_days", "streak_type": "daily"}'::jsonb, 'Fortnight Fame', 31),
(32, 4, 'Saver Level 1', 'Successfully reduce total monthly spending by 10% compared to the previous month.', '{"event_type": "total_spending_reduced", "threshold": 10, "time_window": "30_days", "comparison": "percentage_month_over_month"}'::jsonb, 'Efficiency Expert', 32),
(33, 4, 'Positive Trend', 'Maintain a positive net worth growth trend for 30 days.', '{"event_type": "net_worth_trend", "threshold": 30, "time_window": "30_days", "comparison": "positive"}'::jsonb, 'Wealth Builder', 33),
(34, 4, 'Digital Archivist', 'Scan and digitise 20 receipts in a single month.', '{"event_type": "receipt_scanned", "threshold": 20, "time_window": "30_days"}'::jsonb, 'Scanner Supreme', 34),
(35, 4, 'Budget Master', 'Stay under your "Spent Last 30 Days" limit for one full calendar month.', '{"event_type": "monthly_limit_maintained", "threshold": 30, "time_window": "30_days", "comparison": "under"}'::jsonb, 'Zero Overages', 35),
(36, 4, 'The Centurion', 'Reach a total tracked spend of $100,000 GYD to see a full high-value spending profile.', '{"event_type": "total_spend_threshold", "threshold": 100000, "time_window": null, "comparison": "gte"}'::jsonb, 'High Roller', 36),
(37, 4, 'Habit Former', 'Log spending for 21 consecutive days.', '{"event_type": "transaction_logged", "threshold": 21, "time_window": "21_days", "streak_type": "daily"}'::jsonb, 'Habitual User', 37),
(38, 4, 'Progress Tracker', 'Ask the AI to compare your progress over multiple weeks.', '{"event_type": "ai_chat_used", "threshold": 1, "time_window": null, "pattern": "progress|compare|trend|weeks"}'::jsonb, 'Trend Spotter', 38),
(39, 4, 'Cash Transparency', 'Track 100% of your cash withdrawals and their subsequent spending for a month.', '{"event_type": "cash_tracking_complete", "threshold": 100, "time_window": "30_days", "comparison": "percentage"}'::jsonb, 'Cash Vision', 39),
(40, 4, 'Daily Discipline', 'Keep your "Average Daily" spend under your target for 30 consecutive days.', '{"event_type": "daily_target_achieved", "threshold": 30, "time_window": "30_days", "streak_type": "daily"}'::jsonb, 'Daily Zen', 40),
(41, 4, 'Data Dynamo', 'Categorise 100 total transactions (manual or scanned).', '{"event_type": "transactions_categorized", "threshold": 100, "time_window": null}'::jsonb, 'Data Giant', 41),
(42, 4, 'Long Distance', 'Create and achieve a long-term goal that spans 60 days.', '{"event_type": "long_term_goal_achieved", "threshold": 60, "time_window": "60_days"}'::jsonb, 'Marathoner', 42),
(43, 4, 'Value Creator', 'Increase your tracked Net Worth by 5% through improved spending awareness.', '{"event_type": "net_worth_increase", "threshold": 5, "time_window": null, "comparison": "percentage"}'::jsonb, 'Prosperity', 43),
(44, 4, 'The Conversationalist', 'Interact with the Stashway AI for insights every day for a week.', '{"event_type": "ai_chat_used", "threshold": 7, "time_window": "7_days", "streak_type": "daily"}'::jsonb, 'AI Partner', 44),
(45, 4, 'Report Specialist', 'Export and review four consecutive weekly spending reports.', '{"event_type": "report_exported", "threshold": 4, "time_window": "28_days", "format": "weekly"}'::jsonb, 'Analyst Pro', 45),

-- Phase 5: Financial Mastery (Goals 46-50)
(46, 5, 'Century Streak', 'Maintain a 100-day transaction logging streak.', '{"event_type": "transaction_logged", "threshold": 100, "time_window": "100_days", "streak_type": "daily"}'::jsonb, 'Centurion Streak', 46),
(47, 5, 'Efficiency Master', 'Achieve a "Spent Last 30 Days" goal that is 20% lower than your initial starting average.', '{"event_type": "spending_reduced_vs_baseline", "threshold": 20, "time_window": "30_days", "comparison": "percentage_vs_baseline"}'::jsonb, 'Financial Ninja', 47),
(48, 5, 'Total Visibility', 'Log every single expense, including the smallest cash transactions, for 90 days.', '{"event_type": "complete_logging_streak", "threshold": 90, "time_window": "90_days", "streak_type": "daily", "completeness": 100}'::jsonb, 'Financial Zen', 48),
(49, 5, 'Wealth Milestone', 'Reach a net worth milestone (e.g., $500,000 GYD tracked) through diligent saving and tracking.', '{"event_type": "net_worth_threshold", "threshold": 500000, "time_window": null, "comparison": "gte"}'::jsonb, 'Fortune Builder', 49),
(50, 5, 'Stashway Legend', 'Complete all 49 previous goals.', '{"event_type": "all_goals_completed", "threshold": 49, "time_window": null}'::jsonb, 'Ultimate Stashway Legend', 50)
ON CONFLICT (id) DO NOTHING;

-- Insert Badges (matching each goal)
INSERT INTO badges (badge_name, badge_description, icon_key, goal_id) VALUES
('The Explorer', 'Welcome to Stashway! You''ve taken your first step.', 'explorer', 1),
('Anchor Point', 'You''ve established your financial foundation.', 'anchor', 2),
('Paperless Pioneer', 'Ready to go digital with your receipts.', 'paperless', 3),
('Small Talker', 'You''ve made first contact with your financial AI.', 'chat', 4),
('Goal Setter', 'You''ve set your first financial goal.', 'goal', 5),
('Scan Starter', 'Your first receipt is now digitized!', 'scan', 6),
('Hand-Crafted', 'You manually logged your first transaction.', 'manual', 7),
('Advice Taker', 'You''re open to financial insights.', 'tip', 8),
('Record Keeper', 'You''ve exported your first report.', 'report', 9),
('Clean Slate', 'You''ve organized your first transaction.', 'organize', 10),
('Cash King', 'You''re tracking your physical money.', 'cash', 11),
('Week One', 'You''ve reviewed your weekly spending.', 'week', 12),
('On the Mark', 'You hit your first daily spending target!', 'target', 13),
('Item Finder', 'You''ve mastered the search feature.', 'search', 14),
('Point-to-Point', 'You prefer concise financial advice.', 'concise', 15),
('Three-Day Streak', 'Consistency is key! Three days in a row.', 'streak-3', 16),
('High Volume', 'You''ve scanned 5 receipts in a week.', 'volume', 17),
('Growing Stash', 'Your net worth is on the rise.', 'growth', 18),
('Home Cook', 'You''re cutting back on dining out.', 'home', 19),
('Well-Rounded', 'You track spending across multiple categories.', 'variety', 20),
('Steady Hand', 'You''ve maintained your budget for 15 days.', 'steady', 21),
('Asset Manager', 'You''re managing multiple accounts.', 'multi', 22),
('Calendar Master', 'You''ve reviewed a full month of data.', 'calendar', 23),
('Opportunity Seeker', 'You''re actively looking for ways to save.', 'opportunity', 24),
('Seven-Day Streak', 'A full week of consistent logging!', 'streak-7', 25),
('Local Shopper', 'You''re supporting local businesses.', 'local', 26),
('Report Master', 'You''ve mastered multiple export formats.', 'export', 27),
('Master Planner', 'You''ve set limits across multiple categories.', 'planner', 28),
('Inquiry Expert', 'You ask smart questions about your finances.', 'inquiry', 29),
('Sorting Specialist', 'All your transactions are perfectly categorized.', 'sort', 30),
('Fortnight Fame', 'Two weeks of consistent logging!', 'streak-14', 31),
('Efficiency Expert', 'You reduced spending by 10% month-over-month.', 'efficiency', 32),
('Wealth Builder', 'Your net worth is trending upward.', 'wealth', 33),
('Scanner Supreme', '20 receipts scanned in a month!', 'scanner', 34),
('Zero Overages', 'You stayed under budget for a full month.', 'budget', 35),
('High Roller', 'You''ve tracked $100,000 in spending.', 'high-value', 36),
('Habitual User', 'Three weeks of daily logging!', 'streak-21', 37),
('Trend Spotter', 'You track your progress over time.', 'trend', 38),
('Cash Vision', '100% transparency in cash tracking.', 'transparency', 39),
('Daily Zen', '30 days of perfect daily targets!', 'zen', 40),
('Data Giant', '100 transactions perfectly categorized.', 'data', 41),
('Marathoner', 'You achieved a 60-day goal!', 'marathon', 42),
('Prosperity', 'Your net worth increased by 5%.', 'prosperity', 43),
('AI Partner', 'You chat with AI every day for a week.', 'ai-daily', 44),
('Analyst Pro', 'You''ve exported 4 weekly reports.', 'analyst', 45),
('Centurion Streak', '100 days of consistent logging!', 'streak-100', 46),
('Financial Ninja', 'You reduced spending by 20% vs baseline.', 'ninja', 47),
('Financial Zen', '90 days of complete expense logging.', 'zen-master', 48),
('Fortune Builder', 'You''ve reached $500,000 in net worth!', 'fortune', 49),
('Ultimate Stashway Legend', 'You''ve completed all 49 goals!', 'legend', 50)
ON CONFLICT (badge_name) DO NOTHING;

